#!/bin/bash

export MAC_CONFIG_HOME=$HOME/mac-config

cd $MAC_CONFIG_HOME

git pull origin master

./gitconfig/config
./zsh/config
./profile/config
./vim/config

sh ./nvm/01-install-nvm

sh ./packages/install-firacode
sh ./packages/install-exa
sh ./packages/install-fzf
sh ./packages/install-yarn
