#!/bin/bash

# integrate
alias ibrew='arch -x86_64 /usr/local/bin/brew'
alias mbrew='arch -arm64e /opt/homebrew/bin/brew'
alias ls='exa'
alias ll='exa --long --header --git --icons'
alias la='exa --long --header --git --icons --all'
alias weather='curl -4 wttr.in/brasilia'
alias ghcpr="GH_FORCE_TTY=100% gh pr list | fzf --preview 'GH_FORCE_TTY=100% gh pr view {1}' --preview-window down --ansi --header-lines 3 | awk '{print $1}' | xargs gh pr checkout"