
# SPACESHIP_<SECTION>_<OPTION>
SPACESHIP_PACKAGE_PREFIX="----"
SPACESHIP_PACKAGE_SUFFIX="???"
SPACESHIP_PACKAGE_COLOR="green"


# SPACESHIP_DIR_COLOR=green

SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  python        # Python section
  elm           # Elm section
  elixir        # Elixir section
  xcode         # Xcode section
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  java          # Java section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  gcloud        # Google Cloud Platform section
  venv          # virtualenv section
  conda         # conda virtualenv section
  dotnet        # .NET section
  kubectl       # Kubectl context section
  terraform     # Terraform workspace section
  ibmcloud      # IBM Cloud section
  exec_time     # Execution time
  async         # Async jobs indicator
  line_sep      # Line break
  battery       # Battery level and status
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# SPACESHIP_ASYNC_COLOR
# SPACESHIP_ASYNC_PREFIX
# SPACESHIP_ASYNC_SHOW
# SPACESHIP_ASYNC_SHOW_COUNT
# SPACESHIP_ASYNC_SUFFIX
# SPACESHIP_ASYNC_SYMBOL
# SPACESHIP_AWS_ASYNC
# SPACESHIP_AWS_COLOR
# SPACESHIP_AWS_PREFIX
# SPACESHIP_AWS_SHOW
# SPACESHIP_AWS_SUFFIX
# SPACESHIP_AWS_SYMBOL
# SPACESHIP_BATTERY_ASYNC=false
# SPACESHIP_BATTERY_PREFIX="b "
# SPACESHIP_BATTERY_SHOW=true
# SPACESHIP_BATTERY_SUFFIX=" y"
# SPACESHIP_BATTERY_SYMBOL_CHARGING="+"
# SPACESHIP_BATTERY_SYMBOL_DISCHARGING="-"
# SPACESHIP_BATTERY_SYMBOL_FULL
# SPACESHIP_BATTERY_THRESHOLD
# SPACESHIP_BUN_ASYNC
# SPACESHIP_BUN_COLOR
# SPACESHIP_BUN_PREFIX
# SPACESHIP_BUN_SHOW
# SPACESHIP_BUN_SUFFIX
# SPACESHIP_BUN_SYMBOL
# SPACESHIP_CACHE
SPACESHIP_CHAR_COLOR_SECONDARY="blue"
SPACESHIP_CHAR_COLOR_SUCCESS="green"
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_CHAR_SYMBOL_ROOT="+"
SPACESHIP_CHAR_SYMBOL_SECONDARY="▫️"
SPACESHIP_CHAR_SYMBOL="$(arch)≥:"
SPACESHIP_CHAR_SUFFIX=" "
# SPACESHIP_CONDA_ASYNC
# SPACESHIP_CONDA_COLOR
# SPACESHIP_CONDA_PREFIX
# SPACESHIP_CONDA_SHOW
# SPACESHIP_CONDA_SUFFIX
# SPACESHIP_CONDA_SYMBOL
# SPACESHIP_CONDA_VERBOSE
# SPACESHIP_CONFIG
# SPACESHIP_CONFIG_PATH
SPACESHIP_DIR_COLOR="#09f"
# SPACESHIP_DIR_LOCK_COLOR
# SPACESHIP_DIR_LOCK_SYMBOL
SPACESHIP_DIR_PREFIX="$(arch) "
# SPACESHIP_DIR_SHOW
# SPACESHIP_DIR_SUFFIX
# SPACESHIP_DIR_TRUNC
# SPACESHIP_DIR_TRUNC_PREFIX
# SPACESHIP_DIR_TRUNC_REPO
# SPACESHIP_DOCKER_ASYNC
# SPACESHIP_DOCKER_COLOR
# SPACESHIP_DOCKER_CONTEXT_ASYNC
# SPACESHIP_DOCKER_CONTEXT_PREFIX
# SPACESHIP_DOCKER_CONTEXT_SHOW
# SPACESHIP_DOCKER_CONTEXT_SUFFIX
# SPACESHIP_DOCKER_PREFIX
# SPACESHIP_DOCKER_SHOW
# SPACESHIP_DOCKER_SUFFIX
# SPACESHIP_DOCKER_SYMBOL
# SPACESHIP_DOCKER_VERBOSE
# SPACESHIP_DOTNET_ASYNC
# SPACESHIP_DOTNET_COLOR
# SPACESHIP_DOTNET_PREFIX
# SPACESHIP_DOTNET_SHOW
# SPACESHIP_DOTNET_SUFFIX
# SPACESHIP_DOTNET_SYMBOL
# SPACESHIP_ELIXIR_ASYNC
# SPACESHIP_ELIXIR_COLOR
# SPACESHIP_ELIXIR_DEFAULT_VERSION
# SPACESHIP_ELIXIR_PREFIX
# SPACESHIP_ELIXIR_SHOW
# SPACESHIP_ELIXIR_SUFFIX
# SPACESHIP_ELIXIR_SYMBOL
# SPACESHIP_ELM_ASYNC
# SPACESHIP_ELM_COLOR
# SPACESHIP_ELM_PREFIX
# SPACESHIP_ELM_SHOW
# SPACESHIP_ELM_SUFFIX
# SPACESHIP_ELM_SYMBOL
# SPACESHIP_EXEC_TIME_COLOR
# SPACESHIP_EXEC_TIME_ELAPSED
# SPACESHIP_EXEC_TIME_PRECISION
# SPACESHIP_EXEC_TIME_PREFIX
# SPACESHIP_EXEC_TIME_SHOW
# SPACESHIP_EXEC_TIME_SUFFIX
# SPACESHIP_EXIT_CODE_COLOR
# SPACESHIP_EXIT_CODE_PREFIX
# SPACESHIP_EXIT_CODE_SHOW
# SPACESHIP_EXIT_CODE_SUFFIX
# SPACESHIP_EXIT_CODE_SYMBOL
# SPACESHIP_GCLOUD_ASYNC
# SPACESHIP_GCLOUD_COLOR
# SPACESHIP_GCLOUD_PREFIX
# SPACESHIP_GCLOUD_SHOW
# SPACESHIP_GCLOUD_SUFFIX
# SPACESHIP_GCLOUD_SYMBOL
# SPACESHIP_GIT_ASYNC
# SPACESHIP_GIT_BRANCH_ASYNC
SPACESHIP_GIT_BRANCH_COLOR="#f0c919"
# SPACESHIP_GIT_BRANCH_PREFIX
# SPACESHIP_GIT_BRANCH_SHOW
# SPACESHIP_GIT_BRANCH_SUFFIX
# SPACESHIP_GIT_ORDER
# SPACESHIP_GIT_PREFIX
# SPACESHIP_GIT_SHOW
# SPACESHIP_GIT_STATUS_ADDED
# SPACESHIP_GIT_STATUS_AHEAD
# SPACESHIP_GIT_STATUS_ASYNC
# SPACESHIP_GIT_STATUS_BEHIND
SPACESHIP_GIT_STATUS_COLOR="#ff8020"
# SPACESHIP_GIT_STATUS_DELETED
# SPACESHIP_GIT_STATUS_DIVERGED
# SPACESHIP_GIT_STATUS_MODIFIED
# SPACESHIP_GIT_STATUS_PREFIX
# SPACESHIP_GIT_STATUS_RENAMED
# SPACESHIP_GIT_STATUS_SHOW
# SPACESHIP_GIT_STATUS_STASHED
# SPACESHIP_GIT_STATUS_SUFFIX
# SPACESHIP_GIT_STATUS_UNMERGED
# SPACESHIP_GIT_STATUS_UNTRACKED
# SPACESHIP_GIT_SUFFIX
# SPACESHIP_GIT_SYMBOL
# SPACESHIP_GOLANG_ASYNC
# SPACESHIP_GOLANG_COLOR
# SPACESHIP_GOLANG_PREFIX
# SPACESHIP_GOLANG_SHOW
# SPACESHIP_GOLANG_SUFFIX
# SPACESHIP_GOLANG_SYMBOL
# SPACESHIP_HASKELL_ASYNC
# SPACESHIP_HASKELL_COLOR
# SPACESHIP_HASKELL_PREFIX
# SPACESHIP_HASKELL_SHOW
# SPACESHIP_HASKELL_SUFFIX
# SPACESHIP_HASKELL_SYMBOL
# SPACESHIP_HG_ASYNC
# SPACESHIP_HG_BRANCH_ASYNC
# SPACESHIP_HG_BRANCH_COLOR
# SPACESHIP_HG_BRANCH_PREFIX
# SPACESHIP_HG_BRANCH_SHOW
# SPACESHIP_HG_BRANCH_SUFFIX
# SPACESHIP_HG_ORDER
# SPACESHIP_HG_PREFIX
# SPACESHIP_HG_SHOW
# SPACESHIP_HG_STATUD_MODIFIED
# SPACESHIP_HG_STATUS_ADDED
# SPACESHIP_HG_STATUS_ASYNC
# SPACESHIP_HG_STATUS_COLOR
# SPACESHIP_HG_STATUS_DELETED
# SPACESHIP_HG_STATUS_MODIFIED
# SPACESHIP_HG_STATUS_PREFIX
# SPACESHIP_HG_STATUS_SHOW
# SPACESHIP_HG_STATUS_SUFFIX
# SPACESHIP_HG_STATUS_UNTRACKED
# SPACESHIP_HG_SUFFIX
# SPACESHIP_HG_SYMBOL
# SPACESHIP_HOST_COLOR
# SPACESHIP_HOST_COLOR_SSH
# SPACESHIP_HOST_PREFIX
# SPACESHIP_HOST_SHOW
# SPACESHIP_HOST_SHOW_FULL
# SPACESHIP_HOST_SUFFIX
# SPACESHIP_IBMCLOUD_ASYNC
# SPACESHIP_IBMCLOUD_COLOR
# SPACESHIP_IBMCLOUD_PREFIX
# SPACESHIP_IBMCLOUD_SHOW
# SPACESHIP_IBMCLOUD_SUFFIX
# SPACESHIP_IBMCLOUD_SYMBOL
# SPACESHIP_JAVA_ASYNC
# SPACESHIP_JAVA_COLOR
# SPACESHIP_JAVA_PREFIX
# SPACESHIP_JAVA_SHOW
# SPACESHIP_JAVA_SUFFIX
# SPACESHIP_JAVA_SYMBOL
# SPACESHIP_JOBS
# SPACESHIP_JOBS_AMOUNT_PREFIX
# SPACESHIP_JOBS_AMOUNT_SUFFIX
# SPACESHIP_JOBS_AMOUNT_THRESHOLD
# SPACESHIP_JOBS_COLOR
# SPACESHIP_JOBS_PREFIX
# SPACESHIP_JOBS_SHOW
# SPACESHIP_JOBS_SUFFIX
# SPACESHIP_JOBS_SYMBOL
# SPACESHIP_JULIA_ASYNC
# SPACESHIP_JULIA_COLOR
# SPACESHIP_JULIA_PREFIX
# SPACESHIP_JULIA_SHOW
# SPACESHIP_JULIA_SUFFIX
# SPACESHIP_JULIA_SYMBOL
# SPACESHIP_KUBECTL_ASYNC
# SPACESHIP_KUBECTL_COLOR
# SPACESHIP_KUBECTL_CONTEXT_ASYNC
# SPACESHIP_KUBECTL_CONTEXT_COLOR
# SPACESHIP_KUBECTL_CONTEXT_COLOR_GROUPS
# SPACESHIP_KUBECTL_CONTEXT_PREFIX
# SPACESHIP_KUBECTL_CONTEXT_SHOW
# SPACESHIP_KUBECTL_CONTEXT_SHOW_NAMESPACE
# SPACESHIP_KUBECTL_CONTEXT_SUFFIX
# SPACESHIP_KUBECTL_PREFIX
# SPACESHIP_KUBECTL_SHOW
# SPACESHIP_KUBECTL_SUFFIX
# SPACESHIP_KUBECTL_SYMBOL
# SPACESHIP_KUBECTL_VERSION_ASYNC
# SPACESHIP_KUBECTL_VERSION_COLOR
# SPACESHIP_KUBECTL_VERSION_PREFIX
# SPACESHIP_KUBECTL_VERSION_SHOW
# SPACESHIP_KUBECTL_VERSION_SUFFIX
# SPACESHIP_LIBS
# SPACESHIP_NODE_ASYNC
# SPACESHIP_NODE_COLOR
# SPACESHIP_NODE_DEFAULT_VERSION
SPACESHIP_NODE_PREFIX=""
# SPACESHIP_NODE_SHOW=true
# SPACESHIP_NODE_SUFFIX
# SPACESHIP_NODE_SYMBOL
# SPACESHIP_PACKAGE_ASYNC
# SPACESHIP_PACKAGE_COLOR
# SPACESHIP_PACKAGE_ORDER
# SPACESHIP_PACKAGE_PREFIX
# SPACESHIP_PACKAGE_SHOW
# SPACESHIP_PACKAGE_SHOW_PRIVATE
# SPACESHIP_PACKAGE_SUFFIX
# SPACESHIP_PACKAGE_SYMBOL
# SPACESHIP_PHP_ASYNC
# SPACESHIP_PHP_COLOR
# SPACESHIP_PHP_PREFIX
# SPACESHIP_PHP_SHOW
# SPACESHIP_PHP_SUFFIX
# SPACESHIP_PHP_SYMBOL
SPACESHIP_PROMPT_ADD_NEWLINE="true"
# SPACESHIP_PROMPT_ASYNC
SPACESHIP_PROMPT_DEFAULT_PREFIX="$(arch): "
SPACESHIP_PROMPT_DEFAULT_SUFFIX="$(arch)::"
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
# SPACESHIP_PROMPT_ORDER
# SPACESHIP_PROMPT_PREFIXES_SHOW
# SPACESHIP_PROMPT_SEPARATE_LINE
# SPACESHIP_PROMPT_SUFFIXES_SHOW
# SPACESHIP_PYTHON_ASYNC
# SPACESHIP_PYTHON_COLOR
# SPACESHIP_PYTHON_PREFIX
# SPACESHIP_PYTHON_SHOW
# SPACESHIP_PYTHON_SUFFIX
# SPACESHIP_PYTHON_SYMBOL
# SPACESHIP_ROOT
# SPACESHIP_RPROMPT_ORDER
# SPACESHIP_RUBY_ASYNC
# SPACESHIP_RUBY_COLOR
# SPACESHIP_RUBY_PREFIX
# SPACESHIP_RUBY_SHOW
# SPACESHIP_RUBY_SUFFIX
# SPACESHIP_RUBY_SYMBOL
# SPACESHIP_RUST_ASYNC
# SPACESHIP_RUST_COLOR
# SPACESHIP_RUST_PREFIX
# SPACESHIP_RUST_SHOW
# SPACESHIP_RUST_SUFFIX
# SPACESHIP_RUST_SYMBOL
# SPACESHIP_RUST_VERBOSE_VERSION
# SPACESHIP_SWIFT_ASYNC
# SPACESHIP_SWIFT_COLOR
# SPACESHIP_SWIFT_PREFIX
# SPACESHIP_SWIFT_SHOW_GLOBAL
# SPACESHIP_SWIFT_SHOW_LOCAL
# SPACESHIP_SWIFT_SUFFIX
# SPACESHIP_SWIFT_SYMBOL
# SPACESHIP_TERRAFORM_ASYNC
# SPACESHIP_TERRAFORM_COLOR
# SPACESHIP_TERRAFORM_PREFIX
# SPACESHIP_TERRAFORM_SHOW
# SPACESHIP_TERRAFORM_SUFFIX
# SPACESHIP_TERRAFORM_SYMBOL
# SPACESHIP_TIME_12HR
# SPACESHIP_TIME_COLOR
# SPACESHIP_TIME_FORMAT
# SPACESHIP_TIME_PREFIX
# SPACESHIP_TIME_SHOW
# SPACESHIP_TIME_SUFFIX
# SPACESHIP_USER_COLOR
# SPACESHIP_USER_COLOR_ROOT
# SPACESHIP_USER_PREFIX
# SPACESHIP_USER_SHOW
# SPACESHIP_USER_SUFFIX
# SPACESHIP_VENV_ASYNC
# SPACESHIP_VENV_COLOR
# SPACESHIP_VENV_GENERIC_NAMES
# SPACESHIP_VENV_PREFIX
# SPACESHIP_VENV_SHOW
# SPACESHIP_VENV_SUFFIX
# SPACESHIP_VENV_SYMBOL
# SPACESHIP_VERSION
# SPACESHIP_XCODE_ASYNC
# SPACESHIP_XCODE_COLOR
# SPACESHIP_XCODE_PREFIX
# SPACESHIP_XCODE_SHOW_GLOBAL
# SPACESHIP_XCODE_SHOW_LOCAL
# SPACESHIP_XCODE_SUFFIX
# SPACESHIP_XCODE_SYMBOL